### PR TITLE
add an option to install pre-releases

### PR DESCRIPTION
**Pull request by felipesanches**

### CODE REVIEW

**Comment by felipesanches** [comment]
@chrissimpkins can you review this PR, please?

**Review by chrissimpkins — APPROVED** [review]
LGTM.

Thank you very much Felipe!  I'll update the README docs and push a new release with the update here.

**Comment by felipesanches** [comment]
Maybe you could wait for my additional PR with the extras config settings discussed at #165 

Or alternatively you may cut another release once I do that ;-)

**Comment by chrissimpkins** [comment]
Releases are quick and simple.  We can prep one anytime we want to push changes. And anyone can execute the Action directly from the master branch sources if I am slow on the release. :) 

No rush.  We'll integrate it whenever it is ready.

**Comment by felipesanches** [comment]
cool, thanks!

**Comment by chrissimpkins** [comment]
These changes are available in v1.1.0, also tracked with the v1 release tag in the Action configuration.  You should be able to use either to test that it works.  Let me know if you run into any issues.  Thanks again for adding it Felipe!

**Comment by chrissimpkins** [comment]
https://github.com/marketplace/actions/font-bakery-ci

**Pull request merged**
